services:
  hazelcast1:
    image: hazelcast/hazelcast:5.4
    container_name: hz1
    ports:
      - "5701:5701"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/hazelcast.yaml
    environment:
      HAZELCAST_CONFIG: /opt/hazelcast/hazelcast.yaml

  hazelcast2:
    image: hazelcast/hazelcast:5.4
    container_name: hz2
    ports:
      - "5702:5701"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/hazelcast.yaml
    environment:
      HAZELCAST_CONFIG: /opt/hazelcast/hazelcast.yaml

  hazelcast3:
    image: hazelcast/hazelcast:5.4
    container_name: hz3
    ports:
      - "5703:5701"
    volumes:
      - ./hazelcast.yaml:/opt/hazelcast/hazelcast.yaml
    environment:
      HAZELCAST_CONFIG: /opt/hazelcast/hazelcast.yaml
  
  python-client:
    build: .
    container_name: hz-client
    depends_on:
      - hazelcast1
      - hazelcast2
      - hazelcast3
    environment:
      - PYTHONUNBUFFERED=1
