services:
  database-lab3:
    image: postgres:16
    container_name: postgres-lab3
    ports:
      - "5432:5432"
    volumes:
      - postgre-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_counter_db
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 0.5s
          retries: 30

  python-client:
      build: .
      container_name: python-client
      depends_on:
        database-lab3: 
          condition: service_healthy
      environment:
        PYTHONUNBUFFERED: 1


volumes:
  postgre-data: